global_frame: map
robot_base_frame: base_footprint
resolution: 0.05
height: 30.0
width: 30.0
origin_x: -15.0
origin_y: -15.0
track_unknown_space: true
always_send_full_costmap: true
update_frequency: 10.0
publish_frequency: 2.0
footprint: [[0.55,-0.32],[0.55,0.32],[0.45,0.32],[0.45,-0.32]]
footprint_padding: 0.0

obstacles:
  enabled: true
  footprint_clearing_enabled: true
  combination_method: 1

plugins:
  - {name: obstacles,  type: "costmap_2d::ObstacleLayer" }
